### ISSUE TITLE
"You reported a problem..." message is wrongly displayed without submitting one

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/blok#159]
[Affected versions]:
- Nightly 52.0a1
- Blok v1.0rc10

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Blok add-on (v1.0rc10) is installed and enabled on a new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to a website that tracks user actions.
2. Click on the "Blok" icon in the address bar.
3. Click on the "Report a problem" button.
4. Without selecting any option or clicking the "Submit" button, click on the back arrow button at the left side of the panel.
5. Observe the panel behaviour.

[Expected result]:
- The default messages should be displayed in the panel.

[Actual result]:
- "You reported a problem..." message is wrongly displayed.

[Notes]:
- "You reported a problem..." message should be displayed only after the user clicks on the "Submit" button.
- Added a screen recording with the issue: https://goo.gl/Ns5AcU
![blok_reportaproblemmessage](https://cloud.githubusercontent.com/assets/20083658/18704929/aed2848e-7ff4-11e6-905b-a2871f554aa0.gif)

**Comment by groovecoder** [comment]
Classifying as UX enhancement. The user *has* submitted a problem with the page as soon as they click "Report a problem". The problem report has no breakage details or feedback notes, but [we record that they reported a problem](https://github.com/mozilla/blok/blob/master/docs/metrics.md#client-side).

**Comment by hoosteeno** [comment]
By presenting a "back" button on the same page as a "submit" button, we are implying the user can back out of their report instead of submt. As currently built, they cannot back out of their report. Suggest one of these to fix:
* Allow user to back out. Don't file report until they click "submit".
* Don't imply user can back out. Give them a "cancel" button, not a "back" button.

In either case I think we may also want to change the wording on the 2nd submit button (below the textarea) to "send" or some other non-"submit" word. I think "submit" has a special meaning on forms -- something inclusive of "send", "commit", and "accomplish this form's one true purpose". We should use it once.

**Comment by groovecoder** [comment]
The wording in the panels say "We've noted the problem" to indicate that we *did* record the problem as soon as they clicked Submit. We want a generic problem report, so we don't fatigue users with so many options to submit a report.

So, I would vote for B: take away the "back" button, and/or change it to something else.

**Comment by johngruen** [comment]
Yeah, B

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest Blok build v1.0.1.
