### ISSUE TITLE
The Tracking Protection icon is missing.

### ISSUE THREAD

**Issue by zer09** [mozilla/blok#179]
The icon of the tracking proctection on the address bar is missing on some websites, like on google and youtube.

ff 49.0.1
Win 7 x64

Thanks

**Comment by clemens-tolboom** [comment]
I do not see the icon either.
- Mac OSX 
- FF 49.0.1
- I have NoScript and Add Block Plus enabled.

@zer09 on what sites __is__ it visible?

**Comment by zer09** [comment]
As far as I remember it worked on

- http://www.keybr.com/page/practice
- https://iconverticons.com/online/
- http://timebie.com/
- http://regexlib.com/
- https://www.vpnbook.com/webproxy
- github

It's something it will work 50/50 (50% working, 50% fail).

**Comment by clemens-tolboom** [comment]
I can confirm the Icon appears on
- https://www.vpnbook.com/webproxy

It failed to appear on
- http://regexlib.com/ which has a console log
  > 10:16:56.501 ReferenceError: urchinTracker is not defined
<anonymous>regexlib.com:358
1regexlib.com:358:9

**Comment by zer09** [comment]
I see the same error on console log for http://regexlib.com/ but the icon is still there. I think the error does nothing for the Tracking Protection.

I also tried to enable/disable the Tracking Protection, and the error still persist. It could be it is a website error on the regexlib.com side.

**Comment by groovecoder** [comment]
This is by design ... see https://github.com/mozilla/blok/issues/11 ...

The tracking protection shield icon will only appear if the add-on blocks requests - made to 3rd party **entities** on the page.

The 3rd-party domains on youtube.com are all owned & operated by the "Google" entity in [the entity list file](https://github.com/mozilla/blok/blob/master/src/js/disconnect-entitylist.json), so the add-on does not block those requests, and so does not appear in the location bar.

**Comment by clemens-tolboom** [comment]
@groovecoder thanks for the explanation.

But you should show the shield in a inavitve way to indicate the tool works IMHO.

And this group / entities list should be accessible through the UI. And preferable editable. I personally don't like the resources list as that looks to me ie Google / doubleclick is not blocked. (maybe I misunderstood this tool?)

**Comment by groovecoder** [comment]
We could change the UI to show the shield icon all the time, but that could also create user blindness to the feature, so (as with all UI) it's hard to harmonize all the goals. 😐 

We intentionally left out displaying the tracking domains, groups, and entities to make the UI as simple as possible and to keep the focus on reporting problems & breakages. In addition, custom block- and entity-lists would make the reporting & breakage data much harder to analyze. (I.e., was the page broken because of a page-wide issue/bug, or did the user have a custom list configured?)

We will look at the data we're getting back, ask users some follow-up qualitative questions about the UI, and probably file new UI enhancements. This one is a good idea ... I'd probably like to A/B test this behavior if we can. We'll see ...
