### ISSUE TITLE
Breakage Analysis: 2016-11-01

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blok#204]
Use [TxP: Blok Executive Summary dashboard](https://sql.telemetry.mozilla.org/dashboard/blok-executive-summary) and [origin break notes query](https://sql.telemetry.mozilla.org/queries/1574/source) to:

* [x] Find the 25 "most problematic"* origins
* [x] Analyze user-submitted notes to understand the problem specifics
* [x] Propose 1-5 break-fix changes we could make
  * Facebook Apps & Games: By far the most problematic domain with the most reported breakages. But it looks like it might be a bug in the Test Pilot experiment/add-on. 😢 
  * Fix twimg.com blocked images
    * Ask Disconnect to remove twimg.com from the block-list? Do we have to ask Twitter to set up a twimg-nocookie.com?
    * Allow all cookie-less image requests?
    * Something else?
  * Down-grade `no element found` from errors to warnings to see if sites can work even if the tracking JS cannot find the element into which it will inject an ad?
  * Shim `utag.js` requests to return a no-op `utag.view()` function.
  * ? What else ?

`*` "most problematic" = # of problem pings * (# of problem pings / total # of pings)

**Comment by groovecoder** [comment]
### Most problematic origins
1. apps.facebook.com (60)
1. codepen.io (42)
1. [www.]drudgereport.com (32)
1. mg.mail.yahoo.com (23)
1. www.forbes.com (18)
1. www.amazon.ca (18)
1. www.cnet.com (16)
1. edition.cnn.com (16)
1. weather.com (15)
1. www.kickstarter.com (15)
1. hootsuite.com (14)
1. pfaw.org (14)
1. outlook.live.com (13)
1. play.spotify.com (12)
1. www.newsblur.com (12)
1. N/A (10)
1. www.chip.de (8)
1. vk.com (7)
1. mozilla.invisionapp.com (6)
1. websummit.net (6)
1. www.youtube.com (5)
1. github.com (3)
1. www.facebook.com (2)
1. twitter.com (2)

**Comment by fmarier** [comment]
> Facebook Apps & Games: By far the most problematic domain with the most reported breakages. But it looks like it might be a bug in the Test Pilot experiment/add-on. 😢

That's a little worrying to me since it suggests that the data we have collected about the add-on may not extend cleanly to the feature in Firefox.

> Fix twimg.com blocked images
> Ask Disconnect to remove twimg.com from the block-list? Do we have to ask Twitter to set up a twimg-nocookie.com?

We can't ask them to remove it from the list. It's their list and if they have identified it as a tracker, it should stay on their list. We could however reach out to them to see if it's something that would qualify for their `Content` category.

> Allow all cookie-less image requests?

Is missing images something that users care a lot about? It's unclear from the Yahoo Mail reports for example because people reported missing ads as breakage.

Also relevant is option 1 from https://docs.google.com/document/d/1TxKCWn0qTgo0hnsKQINka-Jhm69nlbjbClgVWUHt22Y/edit (the approaches that Steve investigated and ultimately rejected).

> Down-grade no element found from errors to warnings to see if sites can work even if the tracking JS cannot find the element into which it will inject an ad?

I don't know about the implications of that and whether or not it would be a feasible thing to implement in Firefox. Might be worth asking the JS team to avoid testing a solution that we can never ship.

> Shim utag.js requests to return a no-op utag.view() function.

Is that just for `weather.com`?

I'm surprised that google-analytics wasn't in the top 25. Are most web developers using it properly now?

**Comment by groovecoder** [comment]
> Is missing images something that users care a lot about? It's unclear from the Yahoo Mail reports for example because people reported missing ads as breakage.

That was actually **my assumption** on first view of Yahoo Mail with the add-on enabled. The user-submitted notes made it more clear that images were missing from email contents.

**Comment by fmarier** [comment]
Looking at the list from https://github.com/mozilla/blok/issues/204#issuecomment-257703414 and removing the items where:

- we don't have enough information to reproduce
- the add-on doesn't match the TP feature
- Facebook login is the cause

we are left with these:

1.  [www.]drudgereport.com (32)
  - Mostly broken images since pbs.twimg.com is on the block-list, and most new images seem to come from pbs.twimg.com
2. mg.mail.yahoo.com (23)
  - Yahoo Mail UI images work; right-hand ad images are gone; users report images inside emails are broken. "The pictures will not show on email.", "blocked pictures in mail that i received. When i turend it off everyhing is fine!"
3. www.forbes.com (18)
  - Users report page just stays blank. A couple users mention that it seems like an ad-blocker-blocker could be halting it?
4. www.cnet.com (16)
  - Users report comments and carousels don't work. Comments are provided by Livefyre, which is on the block-list, but is in the 'Content' section, so it's not blocked. Looks like the JS code in the site is throwing errors when (tracking) DOM elements are missing.
    - no element found 36f11e2c.mpstat.us:1:1
5. edition.cnn.com (16)
  - Unclear ... users report "Other", "video", "images", and "layout" but no notes; a shallow crawl of a few pages shows more "no element found" messages
6. weather.com (15)
  - Majority of users report broken video; couple of JS errors pop up on video pages when blocking ...
    - uncaught exception: Unable to find email endpoint ID. (unknown)
    - ReferenceError: utag is not defined record-dry-streaks-southeast-drought-fall-2016:381:11
      - utag.view seems to be the most problematic call. Maybe we could shim a no-op utag.view for requests to utag.js?
7. outlook.live.com (13)
  - Users report 2 major problems:
    - "Sign out" is broken and/or takes multiple clicks?
    - Images in emails are broken
8. www.youtube.com (5)
  - 1 user reported theater mode button doesn't work; 1 user reported the initial advertisement didn't load, so the main video didn't play either; other users reported TP didn't block ads (like ABP/uBlock)
9. github.com (3)
  - Someone reported "Open in Desktop" doesn't work?

**Comment by groovecoder** [comment]
> Also relevant is option 1 from https://docs.google.com/document/d/1TxKCWn0qTgo0hnsKQINka-Jhm69nlbjbClgVWUHt22Y/edit (the approaches that Steve investigated and ultimately rejected).

The problems listed for allowing requests while stripping/blocking cookies are against active content. As far as I know, image requests can't use DOM or localstorage, and can't fingerprint users? So an option to try may still be to allow-and-strip-cookies from [tracking|all] image requests? That could potentially address an entire class of breakage (images) across a number of the most-reported sites (drudgereport.com, mg.mail.yahoo.com, outlook.live.com).

**Comment by fmarier** [comment]
I suppose a good next step would be to investigate manually some of the more problematic ones in this list. For example, missing videos on CNN and Weather.com, Signout in Outlook, theater mode on Youtube.

Alternatively, if the data we are getting from test pilot isn't very actionable, we could go through the reports on [Bugzilla](https://bugzilla.mozilla.org/showdependencytree.cgi?id=1101005&hide_resolved=1) since they have a lot more details. This could help identify some break-fix changes we could make.

For example, when I [dug into one of them](https://bugzilla.mozilla.org/show_bug.cgi?id=1266153#c9), I was able to identify a missing entry in the entitylist. Now that we own this list, we could fix this bug ourselves. Perhaps there are other reports that could be fixed via the entity list as well.

**Comment by fmarier** [comment]
> That could potentially address an entire class of breakage (images) across a number of the most-reported sites (drudgereport.com, mg.mail.yahoo.com, outlook.live.com).

I suspect trackers might switch to loading images like `http://example.com/foo.jpg?USERID=A489BD492CAA98027B8296698CDD10280470CBA8B` or looking at the query string of the referrer URL.

**Comment by groovecoder** [comment]
Ah, and the forbes.com reports in the experiment match [the Forbes bug report on Bugzila](https://bugzilla.mozilla.org/show_bug.cgi?id=1206759) so that's another good option to dig into.

**Comment by groovecoder** [comment]
> I suspect trackers might switch to loading images like http://example.com/foo.jpg?USERID=A489BD492CAA98027B8296698CDD10280470CBA8B or looking at the query string of the referrer URL.

Hmm ... that'd be cool to see if we can predict/measure that somehow ...

**Comment by fmarier** [comment]
In the "See Also" section in the right hand side of https://bugzilla.mozilla.org/show_bug.cgi?id=1101005, there are a number of webcompat reports that could be useful too.

**Comment by groovecoder** [comment]
From the [TXP: Tracking Protection Product Hypothesis doc](https://docs.google.com/document/d/1g1aKpaRuhSu13sU09aKDvKCkXgYzdjXwL4yU06xk17M/edit#heading=h.p258iinee5vv):

> * The experiment produces a test reveals the difference between reported video breakage caused by the block list with no utag.js shim vs a version with a utag.js shim.
> * The experiment provides details regarding the number of tracker requests recorded by twimg.com that can be communicate to both Twitter and Disconnect.
> * Public publication of study findings on Test Pilot.

I will file an issue to build a `utag.js` shim into the test pilot experiment, measure the subsequent difference in video breakage reports, so we can learn if shimming reduces tracking protection breakage.

We are emailing with Disconnect to discuss our findings re: twimg.com.

We will plan to publish this initial breakage data, this analysis, and the fixes (if any) we deploy as a result.

**Comment by groovecoder** [comment]
Closing this issue now that #216 is open. Good to have this analysis here, but need to focus on 1 thing a time right now. 😉
