### ISSUE TITLE
clean-up: break filterRequest out into more functions

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blok#26]
Probably into a new module, and then write tests.

**Comment by groovecoder** [comment]
I've broken some functions out, but I'm having trouble writing tests for background.js because it uses DOM/Web APIs that I guess aren't available in node? E.g., 
```
lcrouch:blok lcrouch$ ./node_modules/.bin/tape tests/test-background.js
/Users/lcrouch/code/blok/js/background.js:6
var testpilotPingChannel = new BroadcastChannel(TESTPILOT_TELEMETRY_CHANNEL)
                               ^

ReferenceError: BroadcastChannel is not defined
```
@rpl - any advice on how to test these bits?

**Comment by rpl** [comment]
@groovecoder yep,there are at least two strategies that we can use:

### inject the dependency explicitly

we can rewrite the module so that any code that uses the BroadcastChannel is inside a function that took the window object as a parameter, e.g.:

exports.backgroundEntryPoint = function({BroadcastChannel}) {
  ...
}

the real background script will call the function with the background `window` object as a parameter,
the test will pass an object with a mock/shim/spy BroadcastChannel, e.g.:

### node `global` global

In node you can define new globals by adding them to the [`global` global](https://nodejs.org/api/globals.html#globals_global), eg.:

```
global.BroadcastChannel = function(...args) {
  this._initArgs = args;
}

// require the module that needs the global after the needed global is defined
var {anExportedFunctionToTest} = require('../js/module-that-uses-the-broadcast-channel');
```

**Comment by groovecoder** [comment]
Closing this. More refactoring/break-out can happen with follow-up issues.
